### ISSUE TITLE
Task 1: Create a menu

### ISSUE THREAD

**Issue by jmahal1** [jmahal1/python-movies#1]
**User Story**

A menu should be created in the terminal that gives a user the option of staying in the menu or quitting. Only if some option for quit is inputted will the program exit, otherwise any other option (valid or invalid) the menu keeps reappearing. 

*persona: the user looking to use a movies search menu
*feature: the menu keeps running until quit option is inputted
*business value: the menu keeps running until the user chooses to quit the program

**Tasks**
- [x] Create first features of a menu in query.py with print and while loop
- [x] In query.py create option for quitting menu (enter q to quit)
- [x] Make loop run indefinitely unless q inputted by user 

**Acceptance Criteria**
1) the menu shows up in terminal for the user
2) the menu allows the user to quit 

**Acceptance Tests**
1) type in anything except quit option to show menu is interminable
2) type "q" for quit to quit out of menu
