### ISSUE TITLE
Task 2: List all the movie names

### ISSUE THREAD

**Issue by jmahal1** [jmahal1/python-movies#3]
**User Story**

This option if selected by the user will list all the movies by title. It can let the viewer simply see what movies are in the menu that can be searched.

*persona: the user looking to use a movies search menu
*feature: the menu gives two options: quit or list movies
*business value: the menu lets user search for a title (or other) until the user chooses to quit the program

**Tasks**
- [x] Create another menu option for user 
- [x] Make a for loop that iterates through the entire list of dictionaries
- [x] Print the name key for each indexed movie

**Acceptance Criteria**
1) menu allows user to quit or list all movies

**Acceptance Tests**
1) user inputs "2", and all the movies are listed
