### ISSUE TITLE
Task 3: Search movies by names

### ISSUE THREAD

**Issue by jmahal1** [jmahal1/python-movies#5]
**User Story**

This option will let the user search for movies by name. It will do so by returning any film name that contains the characters inputted as ordered, regardless of whether it is the full title of the film

*persona: the user looking to use a movies search menu
*feature: the menu shows 3 options: quit, list movies, search movies by name
*business value: the menu lets user list movies or search by inputted name until the user chooses to quit the program

**Tasks**
- [x] Create third menu option to search names
- [x] Prompt user to input a movie name
- [x] Make user input case insensitive 
- [x] Return a list of selections based on input

**Acceptance Criteria**
1) user has third option to input
2) user provides some more input from prompt

**Acceptance Test**
1) user enters input of choice "3"
2) user gives another input (some string) and either gets names or returns to menu
