### ISSUE TITLE
Task 4: Search movies by cast

### ISSUE THREAD

**Issue by jmahal1** [jmahal1/python-movies#7]
**User Story**

The user can search for a cast member, and from that input see all the movies along with the cast member's name contained. The user should be able to put in part of a name (last name only) and get returns.

*persona: the user looking to use a movies search menu
*feature: the menu gives four options: quit, list movies, search by movie title, search by cast member
*business value: the menu lets user search for a cast member (or other) until the user chooses to quit the program

**Tasks**
- [x] Create a fourth menu option
- [x] Prompt the user for a second input
- [x] Created nested for loop searching for indexed list and then indexed list of cast members
- [x] if cast member found, print movie title and cast member

**Acceptance Criteria**
1) Menu option selected
2) Second input provided

**Acceptance Test**
1) User inputs character "4" to search cast member
2) User's second input iterates values in list of cast members within list of dictionaries
